// support radio message types
#define TYPE_ARTILLERY "artillery"
#define TYPE_STRIKE "strike"
#define TYPE_SUPPLY_DROP "supply drop"
#define TYPE_SUPPLY_DROP_REQUEST "supply drop requested"
#define TYPE_CAS_REQUEST "cas request"
#define TYPE_UAV_REQUEST "uav request"
#define TYPE_TRANSPORT_REQUEST "transport request"
#define TYPE_CAS_ABORT "cas abort"
#define TYPE_HELO_DOWN "helo down"