#define GCH_DIALOG_IDD 5280

// Buttons
#define GCH_JOIN_GROUP_BUTTON_IDC 5281
#define GCH_LEAVE_GROUP_BUTTON_IDC 5282
#define GCH_CLOSE_BUTTON_IDC 5283
#define GCH_SET_LEADER_BUTTON_IDC 5284
#define GCH_SET_GROUP_ID_BUTTON_IDC 5285

// edit
#define GCH_SET_GROUP_ID_EDIT_IDC 5286

// combos
#define GCH_CAN_BE_DELETED_COMBO_IDC 5287
#define GCH_CAN_RALLY_COMBO_IDC 5288

// list boxes
#define GCH_SIDE_GROUPS_LISTBOX_IDC 5289
#define GCH_CURRENT_GROUP_LISTBOX_IDC 5290

// indicator texts
#define GCH_LEADER_NAME_INDICATOR_IDC 5291

// misc
#define GCH_SHOW_AI_CHECKBOX_IDC 5292