#define GROUP_CHANGER_DIALOG_IDD 5280

// Buttons
#define GROUP_CHANGER_JOIN_GROUP_BUTTON_IDC 5281
#define GROUP_CHANGER_LEAVE_GROUP_BUTTON_IDC 5282
#define GROUP_CHANGER_CLOSE_BUTTON_IDC 5283

// list boxes
#define GROUP_CHANGER_SIDE_GROUPS_LISTBOX_IDC 5284
#define GROUP_CHANGER_CURRENT_GROUP_LISTBOX_IDC 5285

// indicator texts
#define GROUP_CHANGER_CAN_RALLY_INDICATOR_IDC 5286
#define GROUP_CHANGER_LEADER_NAME_INDICATOR_IDC 5287
#define GROUP_CHANGER_CAN_BE_DELETED_INDICATOR_IDC 5288
#define GROUP_CHANGER_LEADER_IS_PLAYER_INDICATOR_IDC 5289

// misc
#define GROUP_CHANGER_SHOW_AI_CHECKBOX_IDC 5290